### ISSUE TITLE
Adding gilded games util reliably produces a NullPointerException

### ISSUE THREAD

**Issue by koraa** [gildedgames/gilded-games-util#16]
When I add gilded games util to my client, the exception shown below is throws.
The error persists when I remove any mods besides this one.

```
java.lang.NullPointerException: Unexpected error
  at net.minecraft.client.Minecraft.func_71407_l(Unknown Source)
  at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
  at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
  at net.minecraft.client.main.Main.main(SourceFile:148)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

And here's the rest of the relevant info:
- My OS is a very current Arch Linux (updated saturday)
- I use a Lenovo Think Pad X240
- EDIT: OpenJDK 7

```
-- System Details --                                                                                                                                            [25/7444]
Details:                                                                                                                                                        [24/7444]
        Minecraft Version: 1.7.10                                                                                                                               [23/7444]
        Operating System: Linux (amd64) version 4.2.3-1-ARCH                                                                                                    [22/7444]
        Java Version: 1.7.0_85, Oracle Corporation                                                                                                              [21/7444]
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation                                                                              [20/7444]
        Memory: 314297080 bytes (299 MB) / 508891136 bytes (485 MB) up to 1046937600 bytes (998 MB)                                                             [19/7444]
        JVM Flags: 5 total; -Xmx1024M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M                                       [18/7444]
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used                                                                                     [17/7444]
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0                                                                                              [16/7444]
        FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 33 mods loaded, 33 mods active                             [15/7444]
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' [14/7444]
        UCHIJA  mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)                                                                                                [13/7444]
        UCHIJA  FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar)                                                                       [12/7444]
        UCHIJA  Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar)                                                                    [11/7444]
        UCHIJA  Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar)                                                                     [10/7444]
        UCHIJA  PlayerAPI{1.4} [Player API] (minecraft.jar)                                                                                                      [9/7444]
        UCHIJA  RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar)                                                                                         [8/7444]
        UCHIJA  SmartCore{1.0.3} [Smart Core] (minecraft.jar)                                                                                                    [7/7444]
        UCHIJA  mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar)                                                                             [6/7444]
        UCHIJA  gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util-1.7.10-1.7.jar)                                                          [5/7444]
        UCHIJA  battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar)                                          [4/7444]
        UCHIJA  zeldaswordskills{1.7.10-2.2.8b} [Zelda Sword Skills] (1.7.10-zeldaswordskills-2.2.8b.jar)                                                        [3/7444]
        UCHIJA  bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar)                                                                            [2/7444]
        UCHIJA  Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar)                                                                [1/7444]
        UCHIJA  Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar)                                                         [0/7444]
        UCHIJA  Backpack{2.0.0} [Backpack] (backpack-2.0.0-1.7.x.jar) 
        UCHIJA  BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1387-universal.jar) 
        UCHIJA  ChickenShed{1.1.3} [Chicken Shed] (ChickenShed-Mod-1.7.10.jar) 
        UCHIJA  DynamicLights{1.3.9} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
        UCHIJA  DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
        UCHIJA  DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
        UCHIJA  DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
        UCHIJA  DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
        UCHIJA  DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
        UCHIJA  DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
        UCHIJA  DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
        UCHIJA  DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
        UCHIJA  DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
        UCHIJA  IC2{2.2.780-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.780-experimental.jar) 
        UCHIJA  SmartMoving{15.6} [Smart Moving] (SmartMoving-1.7.10-15.6.jar) 
        UCHIJA  SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) 
        UCHIJA  wildcaves3{1.7.10} [Wild Caves 3] (Wild-Caves-Mod-1.7.10.jar) 
        UCHIJA  XaeroMinimap{1.6.5.1} [Xaero's Minimap] (xaeros_minimap_v1.6.5.1_Forge_1.7.10.jar) 
        UCHIJA  zssaddon{1.7.10-alpha-0.0.5-2} [Zelda Sword Skills - Addon] (zeldaswordskillsaddon-v0.0.5a-2-.jar) 
        GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 11.0.3' Renderer: 'Mesa DRI Intel(R) Haswell Mobile '
        Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
        LWJGL: 2.9.1
        OpenGL: Mesa DRI Intel(R) Haswell Mobile  GL version 3.0 Mesa 11.0.3, Intel Open Source Technology Center
        GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

        Is Modded: Definitely; Client brand changed to 'fml,forge'
        Type: Client (map_client.txt)
        Resource Packs: []
        Current Language: English (US)
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Anisotropic Filtering: On (0)
reports/crash-2015-10-18_20.10.23-client.txt
```

**Comment by NuclearAtoms** [comment]
Having the same problem, need answers.
